### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [rtfb/riscv64-in-qemu#34]
Hello!

Thank you for this project!

Could you please add information about license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by rtfb** [comment]
Thanks for reaching out, @vazhnov! We didn't even realize someone has noticed this project, as it's a purely self-educational exercise for me and @rejunity.

Submitted #35.

**Comment by vazhnov** [comment]
I like your idea with https://github.com/rtfb/riscv64-in-qemu/blob/master/scripts/qemu-launcher.py and I prepared some minor changes https://github.com/vazhnov/riscv64-in-qemu/tree/qemu-launcher.py_linter_warnings , but I'm waiting for a license information to be added into project.

**Comment by rtfb** [comment]
The license went in, happy hacking! :-)

**Comment by vazhnov** [comment]
The 2-Clause BSD License — cool!
Thank you!
